import { Product } from "./types"

export const productDummyData: Product[] = [
    {
        id: 1,
        name: "Bouquet 1",
        price: 100,
        image: "/images/product1.jpg",
        categories: ["Bouquet", "Flowers", "Plants"],
        flowerTypes: ["Rose", "Lily", "Tulip"],
        description: "This is a bouquet of flowers",
        stock: 10,
        isFeatured: true,
        isNew: true,
        isBestSeller: true,
        isSale: true,
        isTrending: true,
        isPopular: true,
        isRecommended: true,
    },
    {
        id: 2,
        name: "Bouquet 2",
        price: 200,
        image: "/images/product2.jpg",
        categories: ["Bouquet", "Flowers", "Plants"],
        flowerTypes: ["Rose", "Lily", "Tulip"],
        description: "This is a bouquet of flowers",
        stock: 10,
        isFeatured: true,
        isNew: true,
        isBestSeller: true,
        isSale: true,
        isTrending: true,
        isPopular: true,
        isRecommended: true,
    },
    {
        id: 3,
        name: "Bouquet 3",
        price: 300,
        image: "/images/product3.jpg",
        categories: ["Bouquet", "Flowers", "Plants"],
        flowerTypes: ["Rose", "Lily", "Tulip"],
        description: "This is a bouquet of flowers",
        stock: 10,
        isFeatured: true,
        isNew: true,
        isBestSeller: true,
        isSale: true,
        isTrending: true,
        isPopular: true,
        isRecommended: true,
    },
    {
        id: 4,
        name: "Bouquet 4",
        price: 400,
        image: "/images/product4.jpg",
        categories: ["Bouquet", "Flowers", "Plants"],
        flowerTypes: ["Rose", "Lily", "Tulip"],
        description: "This is a bouquet of flowers",
        stock: 10,
        isFeatured: true,
        isNew: true,
        isBestSeller: true,
        isSale: true,
        isTrending: true,
        isPopular: true,
        isRecommended: true,
    },
    {
        id: 5,
        name: "Bouquet 5",
        price: 500,
        image: "/images/product5.jpg",
        categories: ["Bouquet", "Flowers", "Plants"],
        flowerTypes: ["Rose", "Lily", "Tulip"],
        description: "This is a bouquet of flowers",
        stock: 10,
        isFeatured: true,
        isNew: true,
        isBestSeller: true,
        isSale: true,
        isTrending: true,
        isPopular: true,
        isRecommended: true,
    },
]