import { Category, Product } from "./types"

export const productDummyData: Product[] = [
    {
        id: 1,
        name: "Bouquet 1",
        price: 100,
        image: "/images/category1.jpg",
        categories: ["Bouquet", "Flowers", "Plants"],
        flowerTypes: ["Rose", "Lily", "Tulip"],
        description: "This is a bouquet of flowers",
        stock: 10,
        isFeatured: true,
        isNew: true,
        isBestSeller: true,
        isSale: true,
        isTrending: true,
        isPopular: true,
        isRecommended: true,
    },
    {
        id: 2,
        name: "Bouquet 2",
        price: 200,
        image: "/images/category2.jpg",
        categories: ["Bouquet", "Flowers", "Plants"],
        flowerTypes: ["Rose", "Lily", "Tulip"],
        description: "This is a bouquet of flowers",
        stock: 10,
        isFeatured: true,
        isNew: true,
        isBestSeller: true,
        isSale: true,
        isTrending: true,
        isPopular: true,
        isRecommended: true,
    },
    {
        id: 3,
        name: "Bouquet 3",
        price: 300,
        image: "/images/category3.jpg",
        categories: ["Bouquet", "Flowers", "Plants"],
        flowerTypes: ["Rose", "Lily", "Tulip"],
        description: "This is a bouquet of flowers",
        stock: 10,
        isFeatured: true,
        isNew: true,
        isBestSeller: true,
        isSale: true,
        isTrending: true,
        isPopular: true,
        isRecommended: true,
    },
    {
        id: 4,
        name: "Bouquet 4",
        price: 400,
        image: "/images/category1.jpg",
        categories: ["Bouquet", "Flowers", "Plants"],
        flowerTypes: ["Rose", "Lily", "Tulip"],
        description: "This is a bouquet of flowers",
        stock: 10,
        isFeatured: true,
        isNew: true,
        isBestSeller: true,
        isSale: true,
        isTrending: true,
        isPopular: true,
        isRecommended: true,
    },
    {
        id: 5,
        name: "Bouquet 5",
        price: 500,
        image: "/images/category2.jpg",
        categories: ["Bouquet", "Flowers", "Plants"],
        flowerTypes: ["Rose", "Lily", "Tulip"],
        description: "This is a bouquet of flowers",
        stock: 10,
        isFeatured: true,
        isNew: true,
        isBestSeller: true,
        isSale: true,
        isTrending: true,
        isPopular: true,
        isRecommended: true,
    },
]

export const categoryDummyData: Category[] = [
    {
        id: 1,
        name: "Aqua Bouquet",
        image: "/category1.jpg",
        description: "Fresh hand-tied flowers wrapped with water for lasting beauty",
    },
    {
        id: 2,
        name: "Arrangements",
        image: "/category2.jpg",
        description: "Elegant floral arrangements perfect for any occasion, crafted with premium seasonal flowers",
    },
    {
        id: 3,
        name: "Baskets",
        image: "/category3.jpg",
        description: "Beautiful basket arrangements featuring fresh flowers and decorative elements in rustic containers",
    },
    {
        id: 4,
        name: "Hand-tied Bouquets",
        image: "/category4.jpg",
        description: "Artisanal hand-tied bouquets showcasing the natural beauty of carefully selected blooms",
    },
]